version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=your_jwt_secret
      - EMAIL_USER=your_email_user
      - EMAIL_PASS=your_email_pass
      - FRONTEND_URL=http://localhost:4200
    networks:
      - backend-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - node
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
